### ISSUE TITLE
Twistienav does not work in Angua

### ISSUE THREAD

**Issue by ChrisNel** [HakanS/dokuwiki-plugin-twistienav#1]
Hello,
I am new to Dokuwiki, so possibly a lack of experience or php knowledge. I do not get Twistienav to work correctly in the default Dokuwiki layout.
Instead of the normal >> signs between the youarehere breadcrumbs, I get no signs at all. All crumbs are shown as one line, they remain separatly clickable.
Do you have a solution?
Thanks,
Chris

**Comment by HakanS** [comment]
Do you use URL rewrite? I haven't tested with that. Otherwise, do you have
conflicting plugins?

/Hkan

**Comment by ChrisNel** [comment]
Hakan,
thanks for quick reaction.
I run DOKUwiki in windows mode. I do not believe I use URL rewrite.
I use the the following plug-ins:
acl 
commentsrc 
config 
doctree2filelist 
dw2pdf 
filelist 
imagemap 
info 
plugin 
popularity 
revert 
safefnrecode 
usermanager 

I looked a bit in your sourcecode scritp.js. You refer there to a namespace called "start". My namespaces track do not originate there but in another namespace could this be the problem???

Thanks,
Chris

**Comment by ChrisNel** [comment]
Sorry,
I closed it by accident. Problem is not solved.
Chris

**Comment by SirPaladin** [comment]
Hi i just installed this plugin and have the same problem. 
The "»" in the breadcrumbnavigation betrween Sites and Namespaces is missing. 

When i deactivate twistienav the "»" is back again. 

In my system i use URL rewriting. 
I run Dokuwiki on PHP 5.2... (in Apache / Ubuntu)

My Plugins: 

acl
clearhistory
config
info
plugin
popularity
revert
safefnrecode
twistienav
usermanager

Is there Any solution for the problem jet? Or any idea where to solve it (im new to Dokuwiki and dont know the internal structure jet)

**Comment by HakanS** [comment]
Ok, the plugin doesn't support the "config:start" setting. If you are using this, you have to change line 66 in script.js

```
        if (linkNo == 1 || pagename == 'start') {
```

otherwise the plugin should work with Angua, do you use the default template or have you modified it?

**Comment by ChrisNel** [comment]
Hello Hakan,
thanks for your solution. I replaced "start" by my first pagename. Now it works o.k.
I use the default template. 
Regards,
Chris

**Comment by SirPaladin** [comment]
THX for the awnser. I have also not modified the template. 
I have now solved the problem when using URL-Rewriting and Start-Page-Name staying "start"

the code in line 66 of script.js has to be: 
<code>
if (linkNo == 1 || pagename == '/start' || pagename == 'start') {
</code>

Only now i can see how awesome this plugin is for improving the navigation.
